POST http://localhost:3333/users
Content-Type: application/json

{
    "name": "Ana Carolina Oliveira",
    "cpf": "987.654.321-98",
    "email": "ana.oliveira@example.com",
    "dateOfBirth": "1990-03-25",
    "phone": "+55 (11) 98765-4321",
    "password": "hashedPassword123"
}

###

GET http://localhost:3333/users/1

###

POST  http://localhost:3333/login

    {
    "email": "joao@example.com",
    "password": "sdfsdfsd"
    }